### ISSUE TITLE
User should see labels, not IDs

### ISSUE THREAD

**Issue by ericmtsai** [sfsinger19103/election_anomaly#48]
User should not see ElectionType_Id/OtherElectionType but rather ElectionType. I.e., not (36,'') but rather 'general'. Here’s a transcript:
`Pick the Election record from the database:
       Name  EndDate StartDate ElectionType_Id OtherElectionType \
0   2018 General 2018-11-06 2018-11-06        36           
1 none or unknown    NaT    NaT        42  none or unknown  
 ElectionType  
0   general  
1    other  
Enter the number of the desired Election (or nothing, if your choice is not on the list):
0
Chosen Election is 2018 General`

Similarly, to choose _datafile  user should see ReportingUnit and Election names, not  _Ids.

**Comment by sfsinger19103** [comment]
This is obsolete, given how the interaction works now.
