### ISSUE TITLE
Tell user when necessary parameters are missing from DataLoader() call

### ISSUE THREAD

**Issue by sfsinger19103** [sfsinger19103/election_anomaly#66]

**Comment by sfsinger19103** [comment]
I understand from @ericmtsai that the parameters should be given to track_results(), but user should be able to use DataLoader() without explicitly calling track_results().

**Comment by ericmtsai** [comment]
I'm not sure I totally follow this. However, if you try to create the dataloader class without all the required parameters in your run_time.par file, the program doesn't allow you to go any further and reports back the missing params. For example, please try deleting the juris_name line out of the param file, then doing this:
```
from election_anomaly import DataLoader
dataloader = DataLoader()
```

You should see a helpful message.
